### ISSUE TITLE
Suggestion: SteamLite

### ISSUE THREAD

**Issue by ghost** [lnx00/Fedoraloader#10]
Can you please add a checkbox to run Steam with this commandline : -no-browser +open steam://open/minigameslist

**Comment by johnathon-walnut** [comment]
Alternatively, maybe a text box where you can input whatever steam args you want that saves to a file?

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/171345019-96071ffa-83ca-4a73-83e0-6168daffbec2.png)

like the ability to just shove it all in here.

**Comment by lnx00** [comment]
I have added an option to add custom steam launch options. You can try it here:
https://github.com/lnx00/Fedoraloader/releases/tag/beta-1.6
