### ISSUE TITLE
Steam - Fatal Error (Failed to load steamui.dll)

### ISSUE THREAD

**Issue by mr-nv** [lnx00/Fedoraloader#14]
![image](https://user-images.githubusercontent.com/31269663/174420462-2a835441-fbc4-4a8f-bd6b-78e6b6e7cc89.png)
happens only if you have vac bypass enabled

**Comment by mr-nv** [comment]
lol this happens only when i start fedoraloader from my browser's downloads page

**Comment by xxmyn** [comment]
probably isn't starting as admin if you're opening it through your browser.

please close this issue.

**Comment by mr-nv** [comment]
it is starting from admin tho
