### ISSUE TITLE
Failed to load steamui.dll when re-opening steam

### ISSUE THREAD

**Issue by VOID-Nightmare** [lnx00/Fedoraloader#15]
After opening the program and pressing the "Load" button, the subtext under it says "closing steam..." "opening steam..."

Steam closes and then re-opens but warns of a Fatal Error where it failed to load a .dll file named steamui

![image](https://user-images.githubusercontent.com/108096465/175452369-ccacf235-1b65-4c5a-b3df-a7e2369baaf5.png)

I have had other issues with fedoraloader but I'm going to assume that this is the cause of them.

**Comment by HutchyBean** [comment]
Splendid
