### ISSUE TITLE
Central directory not found

### ISSUE THREAD

**Issue by FFJ11** [lnx00/Fedoraloader#19]
![image](https://user-images.githubusercontent.com/102504389/177134700-6ec5bf6a-2383-4277-850d-646386b4b063.png)

**Comment by xxmyn** [comment]
this issue is caused by a recent transfer of the repo, please be patient while lnx fixes it

**Comment by THEMASTEROFALL3** [comment]
is there an eta or a discord i could possibly join to see when it gets fixed?

**Comment by lnx00** [comment]
Fixed in the newest version:
https://github.com/lnx00/Fedoraloader/releases/latest/
