### ISSUE TITLE
ReadProcessMemory or WriteProcessMemory error

### ISSUE THREAD

**Issue by Sribistree** [lnx00/Fedoraloader#20]
When I'm trying to inject on Windows 7 in says ReadProcessMemory or WriteProcessMemory was completed only partially.
Then the words on Fedoraloader stop on Starting Steam... , but the game and steam still launching,and when the game launched it isn't injected,I don't even know what to do with i
![Скриншот 05-07-2022 152327](https://user-images.githubusercontent.com/108720288/177275434-d21c1873-a769-4720-af51-2bbdda5387d7.png)
![Скриншот 05-07-2022 173829](https://user-images.githubusercontent.com/108720288/177275650-fcf2170c-95ab-4b94-abb8-05e7c114ea07.png)
![Скриншот 05-07-2022 173855](https://user-images.githubusercontent.com/108720288/177275655-1600696b-6b5f-4080-843b-04f27e10a61b.png)
t

**Comment by PeterPumpkinEater69real** [comment]
> Please note that Windows 7 is not supported anymore and you should switch to Windows 10.

**Comment by PeterPumpkinEater69real** [comment]
> 
> But my friend has same Windows 7 and it works on his PC

its not supported and nobody will help you with it

**Comment by johnathon-walnut** [comment]
> > > Please note that Windows 7 is not supported anymore and you should switch to Windows 10.
> 
> But my friend has same Windows 7 and it works on his PC

Regardless of if it works for your friend, windows 7 isn't supported, use windows 10

**Comment by Sribistree** [comment]
> > > > Please note that Windows 7 is not supported anymore and you should switch to Windows 10.
> > 
> > 
> > But my friend has same Windows 7 and it works on his PC
> 
> Regardless of if it works for your friend, windows 7 isn't supported, use windows 10

I literally can't,I don't have enough RAM for it

**Comment by johnathon-walnut** [comment]
¯\_(ツ)_/¯

**Comment by PeterPumpkinEater69real** [comment]
> 
> I literally can't,I don't have enough RAM for it
Not out problem chief

**Comment by xxmyn** [comment]
"it works for my friend that means you have to make it work for me and that it secretly is supported!!!"

**Comment by HARrhhv2** [comment]
> > > > > Please note that Windows 7 is not supported anymore and you should switch to Windows 10.
> > > 
> > > 
> > > But my friend has same Windows 7 and it works on his PC
> > 
> > 
> > Regardless of if it works for your friend, windows 7 isn't supported, use windows 10
> 
> I literally can't,I don't have enough RAM for it

😂🤣🤣🤣🤣
