### ISSUE TITLE
fedoraloader doesnt injects

### ISSUE THREAD

**Issue by AlexFlipH1** [lnx00/Fedoraloader#27]
no idea why

**Comment by AlexFlipH1** [comment]
no respond????

**Comment by lnx00** [comment]
Check your Anti-Virus

**Comment by AlexFlipH1** [comment]
anti virus doesnt do nothing its disabled i upgraded from windows 10 to windows 11 and i cant use fedorawave any more

**Comment by AlexFlipH1** [comment]
and a lot features from windows 11 are missing

**Comment by AlexFlipH1** [comment]
i dont know what fedorawave needs to be injected since i just upgraded

**Comment by canedoly** [comment]
fedoraware works best on windows 10

**Comment by AlexFlipH1** [comment]
i do know but it works slow on windows 10 when i downgrade it to windows 10 and saw it its lagging so hard so i had to go back

**Comment by AlexFlipH1** [comment]
and entire features were missing even anti virus

**Comment by AlexFlipH1** [comment]
only im hoping is for a dev to respond why it doesnt works since i upgraded from windows 10

**Comment by johnathon-walnut** [comment]
Nobody knows, solution is to go back to Windows 10. If you're complaining about lag you clearly don't have a PC capable of running anything so I'm not sure why you even bother

**Comment by AlexFlipH1** [comment]
windows 11 worked for my friend but onlyim thinking is the features are missing and fedoraloader doesnt works by that

**Comment by johnathon-walnut** [comment]
Read above

**Comment by AlexFlipH1** [comment]
listen here you littie shit i said i just upgraded from windows 10 i wont fucking go back to windows 10

**Comment by Capybaron** [comment]
> listen here you littie shit i said i just upgraded from windows 10 i wont fucking go back to windows 10

Shut the fuck up

**Comment by johnathon-walnut** [comment]
> listen here you littie shit i said i just upgraded from windows 10 i wont fucking go back to windows 10

No need to get nasty, nobody is going to help you if you ignore the only solution to exist :)

**Comment by AlexFlipH1** [comment]
i aint go back to windows 10 just for fedorawave

**Comment by Capybaron** [comment]
> i aint go back to windows 10 just for fedorawave

Too bad then

**Comment by johnathon-walnut** [comment]
Guess you're not using it at all then :) I'm certainly not going to try help you with this anymore. 
https://github.com/lnx00/Fedoraloader#issues-with-fedoraware

**Comment by lnx00** [comment]
Banned. Next time do an IQ test before opening issues.
