### ISSUE TITLE
Failed: kernel32 - VirtualProtectEx

### ISSUE THREAD

**Issue by NextZac** [lnx00/Fedoraloader#29]
Tried everything, have all .NET packages installed.

Even when debugging I get said message.
It is somehow unable to hook the functions.

Any ideas?

OS: Windows 11 11.0.22000 | Build 22000
Tried with AV disabled and everything.
It is running as administrator.

**Comment by xxmyn** [comment]
iirc fedoraloader does not support windows 11.

I know that fedoraware does not support windows 11.

**Comment by Capybaron** [comment]
> iirc fedoraloader does not support windows 11.
> 
> I know that fedoraware does not support windows 11.

Wrong! 🖕

**Comment by xxmyn** [comment]
> > iirc fedoraloader does not support windows 11.
> > I know that fedoraware does not support windows 11.
> 
> Wrong! 🖕

maybe partially, but even if fedloader supported win 11, support still wouldnt be offered by fedoraware

**Comment by lnx00** [comment]
Windows 11 is not supported
