### ISSUE TITLE
Failed to download latest build

### ISSUE THREAD

**Issue by SlavicGuy** [lnx00/Fedoraloader#35]
![image](https://user-images.githubusercontent.com/93044516/195610549-ff29fef4-4157-434e-85dd-bdd7b5d83deb.png)

**Comment by setmetatablesadie** [comment]
i'm having this same issue except i can visit that link and im getting this error message
![image](https://user-images.githubusercontent.com/101220729/204097823-eb5c642a-47c4-4617-8026-e93483caabba.png)

**Comment by setmetatablesadie** [comment]
i've also been pasting the dll into the temp folder after it gets deleted and this works (i'm getting several crashes often but im pretty sure it's just a client thing)
