### ISSUE TITLE
try to add jackbail4's bypass (or use danielkrupinski's bypass)

### ISSUE THREAD

**Issue by thegamingboyftw** [lnx00/Fedoraloader#36]
and not the current one on fedoraware crashes and disconnects steam

**Comment by cletusdavid** [comment]
config issue tbh

**Comment by imgladnotu** [comment]
you issue tbh

**Comment by cletusdavid** [comment]
RAGH

**Comment by thegamingboyftw** [comment]
so?

**Comment by cletusdavid** [comment]
vacDisable === TRUE

**Comment by thegamingboyftw** [comment]
but here's the kicker: manual vac ban

**Comment by jailbaiting** [comment]
do it yourself, god forbid the community do something for once amirite :))

**Comment by lnx00** [comment]
Fedoraloader is already using Daniel Krupiński's VAC bypass.

**Comment by thegamingboyftw** [comment]
> Fedoraloader is already using Daniel Krupiński's VAC bypass.

then just use jackbail4's vac bypass tbh
it's way better than danielkrupinski :P

**Comment by imgladnotu** [comment]
ok then, with all your infinite knowledge, tell us why some random noname's vac bypass loader is better than the one made by the person who found the bypass in the first place?
