### ISSUE TITLE
Unclean messy visuals.

### ISSUE THREAD

**Issue by tqkPLARAX** [lnx00/Fedoraloader#38]
All of my visuals are always very messy in fedoraware, it also always has a small transparency.
All visuals are not very clean.
I tried fixing this with "fix chams" but i realised it's not that anyway to fix this?

suggestion for fedoraware: custom name because yes

**Comment by stax132349** [comment]
this is the wrong place to be posting issues, post here: https://github.com/Fedoraware/Fedoraware/issues

**Comment by stax132349** [comment]
and also maybe send a picture of what is happening on your end
