### ISSUE TITLE
injecting

### ISSUE THREAD

**Issue by zQuepzz** [lnx00/Fedoraloader#5]
when i press load it says that the dll is injected but it dosent appear  in my game

**Comment by lnx00** [comment]
Are you on Windows 10 or later?
Did you press the INSERT key to open the menu?
Does it even work with other injectors like Xenos?

**Comment by zQuepzz** [comment]
> Are you on Windows 10 or later? Did you press the INSERT key to open the menu? Does it even work with other injectors like Xenos?

im on windows 11 and it dosent inject with xenos i tried it

**Comment by zQuepzz** [comment]
> Are you on Windows 10 or later? Did you press the INSERT key to open the menu? Does it even work with other injectors like Xenos?

when it's injected thare is a voice line that in saying "im about to start hacking"

**Comment by lnx00** [comment]
> > Are you on Windows 10 or later? Did you press the INSERT key to open the menu? Does it even work with other injectors like Xenos?
> 
> when it's injected thare is a voice line that is saying "im about to start hacking"

This indicates that the injection worked. Try pressing the INSERT key to open the menu

**Comment by zQuepzz** [comment]
> > > Are you on Windows 10 or later? Did you press the INSERT key to open the menu? Does it even work with other injectors like Xenos?
> > 
> > 
> > when it's injected thare is a voice line that is saying "im about to start hacking"
> 
> This indicates that the injection worked. Try pressing the INSERT key to open the menu

thats the problem  the menu dosent appear

**Comment by zQuepzz** [comment]
> > > > Are you on Windows 10 or later? Did you press the INSERT key to open the menu? Does it even work with other injectors like Xenos?
> > > 
> > > 
> > > when it's injected thare is a voice line that is saying "im about to start hacking"
> > 
> > 
> > This indicates that the injection worked. Try pressing the INSERT key to open the menu
> 
> thats the problem the menu dosent appear

i even reseted my whole pc

**Comment by lnx00** [comment]
Then there's not much I can do. If it's not working with Xenos neither, then the issue isn't caused by Fedoraloader

**Comment by zQuepzz** [comment]
> Then there's not much I can do. If it's not working with Xenos neither, then the issue isn't caused by Fedoraloader

ok thank you have a nice day

**Comment by lnx00** [comment]
I've received information that your issue might be caused by the dxlevel option.
Try running the game with the `-dxlevel 95` launch option and see if this helps.
