### ISSUE TITLE
Failed to download latest build

### ISSUE THREAD

**Issue by dive0000** [lnx00/Fedoraloader#8]
Confirmed that this issue is not unique and other users are experiencing this as well.

"Failed to download latest build
No connection could be made because the target machine
actively refused it. (127.0.0.1:9666)"

Other users are getting a different message (without the IP), I believe that mine only has the ip address because I tried to use a proxy to see if it would help.

Clicking okay brings up another message;
"The loader file could not be found!
Do you want to manually select a .dll file?"

**Comment by lnx00** [comment]
Is it working again?

**Comment by dive0000** [comment]
> Is it working again?

yep 
:)
